version: '3.7'
services:
  alfresco-migrator-share:
    image: alfresco-share-alfresco-migrator:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../alfresco-migrator-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: alfresco-migrator-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  alfresco-migrator-acs:
    image: alfresco-content-services-alfresco-migrator:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../alfresco-migrator-platform-docker/target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      JAVA_OPTS: "
        -Dmessaging.broker.url=\"failover:(nio://alfresco-migrator-activemq:61616)?timeout=3000&jms.useCompression=true\"
        "
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - alfresco-migrator-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - alfresco-migrator-postgres

  mariadb:
    image: mariadb:10.7.3
    container_name: mariadb
    volumes:
      - ./mariainit:/docker-entrypoint-initdb.d
      - alfresco-migrator-db-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=alfresco
      - MYSQL_USER=alfresco
      - MYSQL_PASSWORD=alfresco
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin, --wait_timeout=28800]
    ports:
      - "3306:3306"


  alfresco-migrator-ass:
    image: alfresco/alfresco-search-services:2.0.3
    environment:
      SOLR_ALFRESCO_HOST: alfresco-migrator-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: alfresco-migrator-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      # HTTPS or SECRET
      ALFRESCO_SECURE_COMMS: "secret"
      # SHARED SECRET VALUE
      JAVA_TOOL_OPTIONS:
          -Dalfresco.secureComms.secret=secret
    ports:
      - "8983:8983"
    volumes:
      - alfresco-migrator-ass-volume:/opt/alfresco-search-services/contentstore
      - alfresco-migrator-ass-volume:/opt/alfresco-search-services/data
  alfresco-migrator-activemq:
      image: alfresco/alfresco-activemq:5.16.1
      ports:
        - 8161:8161 # Web Console
        - 5672:5672 # AMQP
        - 61616:61616 # OpenWire
        - 61613:61613 # STOMP

volumes:
  alfresco-migrator-acs-volume:
    external: true
  alfresco-migrator-db-volume:
    external: true
  alfresco-migrator-ass-volume:
    external: true
